import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GNB from "@/app/common/components/GNB";
import { HackleProvider, createInstance } from "@hackler/react-sdk";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full max-w-screen-xl mx-auto min-h-screen bg-white">
        <GNB />
        <div className="w-full h-full flex justify-center">{children}</div>
      </body>
    </html>
  );
}
