name: PR Test
on: 
	pull_request:   
    	branches:
        	- test  

jobs: 
	Run Jest:
    	runs-on: [ubuntu-latest] 
        strategy:
          matrix:
            node-version: [8.x, 10.x, 12.x] 
        steps: 
         - uses: actions/checkout@v2
         - name: npm install
           run: npm install
         - name: run test code
           run: npm run test
           run: npm run cypress:run
